language: generic
matrix:
   include:
      # Test Ubuntu Linux 16.04 / Swift 5
       - os: linux
         dist: xenial
         sudo: required
         env:
           - SWIFT_VERSION=swift-5.0-RELEASE
           - SWIFT_URL=https://swift.org/builds/swift-5.0-release/ubuntu1604/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu16.04.tar.gz
         install:
           - export PATH=$(pwd)/tests/$SWIFT_VERSION-ubuntu16.04/usr/bin:"${PATH}"
      # Test Xcode 10.2 / Swift 5
       - os: osx
         osx_image: xcode10.2
addons:
  apt:
    packages:
    - clang
    - pkg-config
script:
  # Setup Linux environment
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then SWIFT_DIR=tests ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir $SWIFT_DIR ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl $SWIFT_URL -s | tar xz -C $SWIFT_DIR &> /dev/null ; fi
  # Run Unit Tests
  - swift test